version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.0.0  # Use the latest stable Selenium Hub image
    container_name: selenium-hub
    ports:
      - "4444:4444"  # Expose port 4444 for Selenium Hub interface

  chrome:
    image: selenium/node-chrome:4.0.0  # Use the latest stable Chrome Node image
    volumes:
      - /dev/shm:/dev/shm  # Reduces memory-related browser crashes
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.0.0  # Use the latest stable Firefox Node image
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
